// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVHrGv3rvsnPKtdYavPZpLB2dyzGTVgxE',
    appId: '1:257131396120:web:a8e09deaed0d251a0dd76d',
    messagingSenderId: '257131396120',
    projectId: 'buskoi-63b8d',
    authDomain: 'buskoi-63b8d.firebaseapp.com',
    storageBucket: 'buskoi-63b8d.appspot.com',
    measurementId: 'G-ZJXEED7NV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTH2FPSWX1ZTk9R4CT6Gh0RwBVUyJGcso',
    appId: '1:257131396120:android:0a89810500fbbbff0dd76d',
    messagingSenderId: '257131396120',
    projectId: 'buskoi-63b8d',
    storageBucket: 'buskoi-63b8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYIPrvrmaKnaVKYCvhYWlqFps0GC9XL0',
    appId: '1:257131396120:ios:029eae7832f03e8e0dd76d',
    messagingSenderId: '257131396120',
    projectId: 'buskoi-63b8d',
    storageBucket: 'buskoi-63b8d.appspot.com',
    androidClientId: '257131396120-qktjv7df2cs338283ngo1fjt7ndu6u28.apps.googleusercontent.com',
    iosClientId: '257131396120-u45gm7hjv5leo9reiccsk0vt9mqacods.apps.googleusercontent.com',
    iosBundleId: 'com.example.busKoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWYIPrvrmaKnaVKYCvhYWlqFps0GC9XL0',
    appId: '1:257131396120:ios:d89c3a132ecdae760dd76d',
    messagingSenderId: '257131396120',
    projectId: 'buskoi-63b8d',
    storageBucket: 'buskoi-63b8d.appspot.com',
    androidClientId: '257131396120-qktjv7df2cs338283ngo1fjt7ndu6u28.apps.googleusercontent.com',
    iosClientId: '257131396120-n1kv2ihfjm9j25ato06l7225bm9r5pj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.busKoi.RunnerTests',
  );
}
